### ISSUE TITLE
Does not support constrained language module

### ISSUE THREAD

**Issue by MoSkinny** [ironmansoftware/powershell-pro-tools#94]
I've updated to the latest version of visual studio 2022 (17.12.1) but continue to get this error occasionally when I open a new instance of visual studio. I haven't had the chance to observe this yet but before upgrading visual studio would freeze and lag and then the performance monitor asks to disable the extension.

Has this been observed by others and is there a fix?

---------------------------
PowerShell Tools for Visual Studio Error
---------------------------
Failed to initialize PowerShell Tools for Visual StudioSystem.Exception: PowerShell Tools for Visual Studio does not support constrained language module.
   at PowerShellTools.HostService.ServiceManagement.Debugging.PowerShellDebuggingService.InitializeRunspace(Int32 processId, PSHost psHost, Boolean sta)
   at PowerShellTools.ServiceManagement.ConnectionManager.OpenClientConnection()
   at PowerShellTools.PowerShellToolsPackage.<InitializePowerShellHostAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeInternalAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeAsync>d__32.MoveNext()
---------------------------
OK   
---------------------------

**Comment by TMA-2** [comment]
I'd take a look at [the documentation on language modes](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.4#constrainedlanguage-mode) and verify you're running in Full Language Mode with `$ExecutionContext.SessionState.LanguageMode`. I wouldn't expect any PS extension to work under Constrained or Restricted as it dampens their access to .NET classes and a lot of features aside from the most basic constants and automatic variables and keywords.
